### ISSUE TITLE
Resource provider conflict for lvm_volume_group

### ISSUE THREAD

**Issue by jflemer-ndp** [chef-cookbooks/lvm#197]
When using the `lvm_volume_group` resource in v5.0.4, I'm seeing an error (with Chef 13) of:
```
NoMethodError: undefined method `physical_volumes' for Chef::Resource::BaseLogicalVolume
```

It looks like two resources both claim to provide `lvm_volume_group`, and the wrong one is being used. Same wrapper cookbook worked using `lvm_volume_group` with v5.0.2.

Base resource, which should not be providing `lvm_volume_group`?

https://github.com/chef-cookbooks/lvm/blob/688f74f1d3d293d3540b77c7a7e5c1e92e26637c/libraries/base_resource_logical_volume.rb#L29-L30

Real/expected resource:

https://github.com/chef-cookbooks/lvm/blob/688f74f1d3d293d3540b77c7a7e5c1e92e26637c/libraries/resource_lvm_volume_group.rb#L29

cc @agwiles
